name: build

on:
  push:
    branches:
      - main
  pull_request:

env:
  FORCE_COLOR: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/npm-install
      - run: npm run lint
      - run: npm run test:cov

      - name: Upload coverage (api-token-authorizer)
        uses: codecov/codecov-action@v2
        with:
          files: ./packages/api-token-authorizer/coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload coverage (commons)
        uses: codecov/codecov-action@v2
        with:
          files: ./packages/commons/coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload coverage (core)
        uses: codecov/codecov-action@v2
        with:
          files: ./packages/core/coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }
      - name: Upload coverage (engine-layer)
        uses: codecov/codecov-action@v2
        with:
          files: ./packages/engine-layer/coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload coverage (infrastructure)
        uses: codecov/codecov-action@v2
        with:
          files: ./packages/infrastructure/coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload coverage (server)
        uses: codecov/codecov-action@v2
        with:
          files: ./packages/server/coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload coverage (lambda)
        uses: codecov/codecov-action@v2
        with:
          files: ./packages/lambda/coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
