name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: [self-hosted, linux, codebuild]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/npm-install
      - run: npm run lint
      - run: npm run test
