name: build

on:
  push:
    branches:
      - main
  pull_request:

env:
  FORCE_COLOR: 1

jobs:
  build:
    strategy:
      matrix:
        runs-on:
          - ubuntu-latest
          - buildjet-4vcpu-ubuntu-2204
          - buildjet-8vcpu-ubuntu-2204
          - buildjet-16vcpu-ubuntu-2204
          - buildjet-32vcpu-ubuntu-2204
    name: Build - ${{matrix.runs-on}}
    runs-on: ${{matrix.runs-on}}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/npm-install
      - run: npm run lint
      - run: npm run test
