name: deploy
on:
  push:
    branches:
      - main
concurrency: deploy
jobs:
  deploy:
    runs-on: [self-hosted, linux, codebuild]
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/npm-install
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: npm run deploy
